import { Skeleton } from '@/components/ui/skeleton'
import { ErrorState } from '@/components/shared/states'
import { useContractInstallments } from '@/features/contracts/hooks/useInstallments'
import { formatDayMonth, formatEGP, todayISO } from '@/lib/format'
import { cn } from '@/lib/utils'
import type { InstallmentRow } from '@/features/contracts/api/installments'

type DisplayStatus = 'paid' | 'partial' | 'overdue' | 'pending' | 'waived'

const statusStyles: Record<DisplayStatus, { bg: string; label: string }> = {
  paid: { bg: 'bg-status-paid-bg text-status-paid', label: 'مدفوع' },
  partial: { bg: 'bg-status-partial-bg text-status-partial', label: 'جزئي' },
  overdue: { bg: 'bg-status-missed-bg text-status-missed', label: 'متأخر' },
  pending: { bg: 'bg-muted text-muted-foreground', label: 'قادم' },
  waived: { bg: 'bg-muted text-muted-foreground', label: 'مُعفى' },
}

/**
 * «متأخر» غير مخزَّن في قاعدة البيانات عمدًا (انظر 00013_installments.sql) —
 * يُشتق هنا من تاريخ الاستحقاق بدل الاعتماد على مهمة ليلية قد تتعطل بصمت.
 * `overdue` is deliberately never stored (see 00013_installments.sql) — derived
 * here from the due date instead of depending on a nightly job that could fail
 * silently.
 */
function displayStatus(installment: InstallmentRow, today: string): DisplayStatus {
  if (installment.status === 'paid') return 'paid'
  if (installment.status === 'waived') return 'waived'
  if (installment.due_date < today) return 'overdue'
  return installment.status === 'partial' ? 'partial' : 'pending'
}

export function InstallmentSchedule({ contractId }: { contractId: string }) {
  const { data: installments, isPending, isError, refetch } = useContractInstallments(contractId)

  if (isPending) {
    return (
      <div className="grid grid-cols-[repeat(auto-fill,minmax(4.5rem,1fr))] gap-px overflow-hidden rounded-lg border bg-border">
        {Array.from({ length: 6 }, (_, i) => (
          <Skeleton key={i} className="h-16 rounded-none" />
        ))}
      </div>
    )
  }
  if (isError) return <ErrorState onRetry={() => void refetch()} className="py-4" />
  // الجدول يُنشأ بمحفّز متزامن مع إضافة العقد، فلا يُفترض وصول فارغ إلا أثناء
  // التحميل الأول — لا تُعرض حالة «لا توجد أقساط».
  // The schedule is generated by a trigger synchronous with contract creation,
  // so an empty result should never really happen outside the initial fetch —
  // no "no installments" empty state is shown.
  if (installments.length === 0) return null

  const today = todayISO()
  const overdueCount = installments.filter((i) => displayStatus(i, today) === 'overdue').length

  return (
    <div>
      <div className="mb-2 flex items-center justify-between">
        <p className="text-xs font-medium text-muted-foreground">جدول الأقساط</p>
        {overdueCount > 0 ? (
          <span className="text-xs font-semibold text-status-missed">
            {overdueCount} {overdueCount === 1 ? 'قسط متأخر' : 'أقساط متأخرة'}
          </span>
        ) : null}
      </div>
      <div className="grid grid-cols-[repeat(auto-fill,minmax(4.5rem,1fr))] gap-px overflow-hidden rounded-lg border bg-border">
        {installments.map((installment) => {
          const status = displayStatus(installment, today)
          const style = statusStyles[status]
          return (
            <div
              key={installment.id}
              className={cn('px-1.5 py-2 text-center', style.bg)}
              title={`القسط رقم ${installment.seq_no}`}
            >
              <p className="truncate text-[10px] font-semibold opacity-80">
                {formatDayMonth(installment.due_date)}
              </p>
              <p className="mt-0.5 truncate text-xs font-bold tabular">
                {status === 'waived' ? '—' : formatEGP(installment.amount_due)}
              </p>
              <p className="mt-0.5 truncate text-[9px] opacity-70">{style.label}</p>
            </div>
          )
        })}
      </div>
    </div>
  )
}
